# Create ansible user
- src: git+git@github.com:public-ansible-roles/create-ansible-user.git

# Configure sshd
- src: git+git@github.com:public-ansible-roles/sshd.git

# Install common packages for all servers
- src: git+git@github.com:public-ansible-roles/common.git

# Install ansible
- src: git+git@github.com:public-ansible-roles/ansible.git

# Install packer
- src: git+git@github.com:public-ansible-roles/packer.git
  version: hotfix

# Install azure-cli
- src: git+git@github.com:public-ansible-roles/azure-cli.git
