# create ansible user
- src: git+git@github.com:public-ansible-roles/create-ansible-user.git

# configure sshd
- src: git+git@github.com:public-ansible-roles/sshd.git

# Install packer
- src: git+git@github.com:public-ansible-roles/packer.git
  version: hotfix

# Install azure-cli
- src: git+git@github.com:public-ansible-roles/azure-cli.git
