---
- hosts: localhost
  gather_facts: no
  become: true
  roles:
    - create-ansible-user

- hosts: localhost
  gather_facts: no
  become: true
  remote_user: ansible
  roles:
    - sshd
    - common
    - ansible
    - packer
    - azure-cli
